data:
  root_dir: "/media/emmanuel/T7/data/sondra/SAN_FRANCISCO_ALOS2"
  dataset: polsf
  batch_size: 8
  accumulation_steps: 4
  num_workers: 4
  valid_ratio: 0.2
  patch_size: [64, 64]

transform:
  name: "SARContrastiveAugmentations"
  params:

nepochs: 40

logging:
  logdir: "./logs"

model:
  class: SegmentationSegformer
  num_channels: 3
  widths: [8, 16, 32, 64]
  depths: [3, 4, 6, 3]
  all_num_heads: [1, 2, 4, 8]
  patch_sizes: [7, 3, 3, 3]
  overlap_sizes: [4, 2, 2, 2]
  reduction_ratios: [8, 4, 2, 1]
  mlp_expansions: [4, 4, 4, 4]
  decoder_channels: 64
  scale_factors: [8, 4, 2, 1]
  drop_prob: 0.1
  upsample_scale_factor: 1
  contrastive: false

loss:
  name: CrossEntropyLoss

optimizer:
  name: AdamW
  params:
    lr: 0.005
    weight_decay: 0.0005

scheduler:
  name: StepLR
  params:
    step_size: 5
    gamma: 0.9

verbose: false
