data:
  root_dir: "/media/emmanuel/T7/data/sondra/SAN_FRANCISCO_ALOS2"
  dataset: polsf
  batch_size: 32
  accumulation_steps: 4
  num_workers: 4
  valid_ratio: 0.2
  patch_size: [128, 128]
  segmentation: True

transform:
  name: "SARContrastiveAugmentations"
  params:

nepochs: 12

logging:
  logdir: "./logs"

model:
  class: SegmentationSegformer
  num_channels: 3
  widths: [8, 16, 32, 64]
  depths: [6, 6, 6, 6]
  all_num_heads: [8, 8, 8, 8]
  patch_sizes: [7, 3, 3, 3]
  overlap_sizes: [4, 2, 2, 2]
  reduction_ratios: [8, 4, 2, 1]
  mlp_expansions: [4, 4, 4, 4]
  decoder_channels: 128
  scale_factors: [8, 4, 2, 1]
  drop_prob: 0.1
  upsample_scale_factor: 4
  contrastive: False
  loss_weights: null

loss:
  name: FocalLoss

optimizer:
  name: AdamW
  params:
    lr: 0.005
    weight_decay: 0.0005

scheduler:
  name: null #CosineAnnealingLR
  params:
    step_size: 5
    gamma: 0.9
    last_epoch: -1
    eta_min: 0
    max_epoch: -1
    max_lr: 0.05
    pct_start: 0.1
    anneal_strategy: "linear"
    cycle_momentum: True
    base_momentum: 0.8
    max_momentum: 0.9
    div_factor: 1

verbose: false
