data:
  root_dir: "~/data"
  dataset: mnist
  batch_size: 32
  accumulation_steps: 4
  num_workers: 4
  valid_ratio: 0.2
  patch_size: [28, 28]   
  segmentation: True

transform:
  name: "SARContrastiveAugmentations"
  params:

nepochs: 40

logging:
  logdir: "./logs"

model:
  class: SegmentationSegformer
  num_channels: 1                # MNIST is 1 channel
  widths: [4, 8, 16, 32]        
  depths: [2, 2, 2, 2]           
  all_num_heads: [1, 1, 2, 2]    
  patch_sizes: [3, 3, 3, 3]      
  overlap_sizes: [1, 1, 1, 1]    
  reduction_ratios: [4, 2, 1, 1] 
  mlp_expansions: [2, 2, 2, 2]   
  decoder_channels: 32          
  scale_factors: [1, 1, 1, 1]    
  drop_prob: 0.1
  upsample_scale_factor: 1      
  contrastive: false

loss:
  name: FocalLoss

optimizer:
  name: AdamW
  params:
    lr: 0.005
    weight_decay: 0.0005

scheduler:
  name: None
  params:
    step_size: 5
    gamma: 0.9
    last_epoch: -1
  params_cosinelr:
    eta_min: 0
    max_epoch: -1
  params_onecyclelr:
    max_lr: 0.05
    pct_start: 0.1
    anneal_strategy: "linear"
    cycle_momentum: True
    base_momentum: 0.8
    max_momentum: 0.9
    div_factor: 1

verbose: false
