_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
data:
    value:
        accumulation_steps: 4
        batch_size: 8
        dataset: polsf
        num_workers: 4
        patch_size:
            - 64
            - 64
        root_dir: /mounts/Datasets1/Polarimetric-SanFrancisco/SAN_FRANCISCO_ALOS2/
        valid_ratio: 0.2
logging:
    value:
        logdir: ./logs
loss:
    value:
        name: CrossEntropyLoss
model:
    value:
        activation: relu
        channels_ratio: 64
        class: SegmentationUNet
        contrastive: false
        downsampling_method: MaxPool
        dropout: 0
        normalization_method: BatchNorm
        num_channels: 3
        num_layers: 4
        track_running_stats: true
        upsample_scale_factor: 1
        upsampling_method: Upsample
nepochs:
    value: 40
optimizer:
    value:
        algo: AdamW
verbose:
    value: false
